language: cpp
services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - doxygen

script: |
  docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/AnalysisTree kreisl/rootcpp17:v6.20.04 /bin/bash -c '
  set -e # exit on failure
  set -x # trace for debug
  source /opt/rh/devtoolset-8/enable
  cd AnalysisTree
  doxygen docs/Doxyfile.in
  mkdir build
  cd build
  cmake ../ -DCMAKE_BUILD_TYPE=Debug -DAnalysisTree_BUILD_TESTS=ON
  make
  ctest'

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: Doxygen//html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
